[build.environment]
  NPM_VERSION = "6.14.15"
  NPM_FLAGS = "--legacy-peer-deps"
[[redirects]]
  from = "/api/*"
  to = "https://cuet-bus-scheduler.herokuapp.com/ctas/v1/:splat"
  status = 200
  force = true