[build.environment]
  NODE_VERSION = "14.18.2"
  NPM_FLAGS = "--legacy-peer-deps"
[[redirects]]
  from = "/api/*"
  to = "https://cuet-bus-scheduler-backend.herokuapp.com/ctas/v1/:splat"
  status = 200
  force = true